import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../src/components/Hero'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ignacio Diaz | Front End Developer | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bilbo+Swash+Caps&family=Birthstone&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Hero />
      </main>

      <footer></footer>
    </>
  )
}

export default Home
